# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('cid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=50)),
                ('pilot_rating', models.CharField(max_length=30)),
                ('atc_rating', models.CharField(max_length=30)),
            ],
        ),
    ]
