# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170203_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('callsign', models.CharField(max_length=10)),
                ('cid', models.CharField(max_length=30)),
                ('planned_aircraft', models.CharField(max_length=8)),
                ('planned_tascruise', models.IntegerField()),
                ('planned_depairport', models.CharField(max_length=4)),
                ('planned_altitude', models.IntegerField()),
                ('planned_destairport', models.CharField(max_length=4)),
                ('planned_deptime', models.TimeField(null=True)),
                ('planned_actdeptime', models.TimeField(null=True)),
                ('planned_altairport', models.CharField(max_length=4)),
                ('planned_remarks', models.CharField(max_length=255)),
                ('planned_route', models.TextField()),
                ('time_logon', models.DateTimeField(null=True)),
                ('Routestring', models.TextField()),
                ('duration', models.TimeField()),
                ('total_distance', models.IntegerField()),
                ('day_night', models.CharField(max_length=1)),
                ('outRamp', models.DateTimeField(null=True)),
                ('offGround', models.DateTimeField(null=True)),
                ('onGround', models.DateTimeField(null=True)),
            ],
        ),
    ]
