# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='inGate',
            field=models.DateTimeField(null=True),
        ),
    ]
