# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_flights_ingate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='date',
            new_name='just_date',
        ),
        migrations.AlterUniqueTogether(
            name='flights',
            unique_together=set([('just_date', 'callsign', 'cid')]),
        ),
    ]
