# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170203_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllers',
            name='id',
        ),
        migrations.AlterField(
            model_name='controllers',
            name='cid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
