# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-05 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170203_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveFlights',
        ),
        migrations.DeleteModel(
            name='Aircrafts',
        ),
        migrations.DeleteModel(
            name='Airlines',
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Isocodes',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
