# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveControllers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('callsign', models.CharField(max_length=10)),
                ('cid', models.CharField(max_length=30)),
                ('clienttype', models.CharField(max_length=10)),
                ('frequency', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('server', models.CharField(max_length=15)),
                ('facilitytype', models.CharField(max_length=30)),
                ('visualrange', models.IntegerField()),
                ('time_logon', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activecontrollers',
            unique_together=set([('datetime', 'callsign', 'cid')]),
        ),
    ]
