# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_delete_activecontrollers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='altitudeString',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
